name: WarpCore
main: RoMo\WarpCore\WarpCore
author: RoMo_Official
version: 3.0.1
api:
  - 5.0.0

permissions:
  warpcore.manage.warp:
    default: op
  warpcore.use.warp:
    default: true

depend:
  - StarGate-Atlantis